controller_list:
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - left_finger_joint
      - right_finger_joint
initial:  # Define initial robot poses per group
  - group: gripper_group
    pose: gripper_close