gripper_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger_joint
    - right_finger_joint
  gains:
    left_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1